# For more info on HTTP files go to https://aka.ms/vs/httpfile
@myhero_dotnet_address = http://localhost:5000
@version = api/v1
@url = {{myhero_dotnet_address}}/{{version}}/search

# /user/by/

### Search GET {{url}}/user/id
GET {{url}}/user/1MIq9KET4EWG21A+qrTxLg==


### Search GET {{url}}/user/by/name
GET {{url}}/user/by/smbaek
#Content-Type: application/json

